/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bdsiproject;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author PCMiguel
 */
public class CompResult extends javax.swing.JDialog {

    PythonConnector pc;
    String prefix;

    /**
     * Creates new form CompResult
     *
     * @param parent
     * @param modal
     * @param result
     */
    public CompResult(java.awt.Frame parent, boolean modal, List<String> result) {
        super(parent, modal);
        try {
            if (result.isEmpty()) {
                JOptionPane.showMessageDialog(parent, "No existen archivos PATHWAY en comun.", "JavaKEGG 1.0: Error", JOptionPane.ERROR_MESSAGE);
                this.dispose();
            } else {
                pc = new PythonConnector();
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                initComponents();
                this.setLocationRelativeTo(null);
                rdOpt1.setText(result.get(0));
                rdOpt2.setText(result.get(1));
                prefix = result.get(0).split("- ")[1];
                for (int i = 2; i < result.size(); i++) {
                    String string = result.get(i);
                    for (Object item : pc.getItems("map" + string, 0)) {
                        //System.out.println(item);
                        cboItemsRes.addItem(string + ": " + (String) item);
                    }
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngType = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        cboItemsRes = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        rdOpt1 = new javax.swing.JRadioButton();
        rdOpt2 = new javax.swing.JRadioButton();
        btnDoVis = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        rdOpt3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JavaKEGG 1.0: Comparación");
        setModal(true);

        jLabel4.setText("Por favor, seleccione el PATHWAY que desee visualizar:");

        jLabel1.setText("Tipo de PATHWAY:");

        btngType.add(rdOpt1);
        rdOpt1.setSelected(true);
        rdOpt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdOpt1ActionPerformed(evt);
            }
        });

        btngType.add(rdOpt2);
        rdOpt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdOpt2ActionPerformed(evt);
            }
        });

        btnDoVis.setText("Visualizar");
        btnDoVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoVisActionPerformed(evt);
            }
        });

        btnExit.setText("Aceptar");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btngType.add(rdOpt3);
        rdOpt3.setText("Ambos");
        rdOpt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdOpt3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDoVis, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdOpt2)
                            .addComponent(rdOpt1)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(cboItemsRes, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdOpt3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboItemsRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdOpt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdOpt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdOpt3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoVis)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDoVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoVisActionPerformed
        if (rdOpt3.isSelected()) {
            prefix = rdOpt1.getText().split("- ")[1];
            pc.visualize(prefix + cboItemsRes.getSelectedItem().toString().split(":")[0]);
            prefix = rdOpt2.getText().split("- ")[1];
            pc.visualize(prefix + cboItemsRes.getSelectedItem().toString().split(":")[0]);
        } else {
            pc.visualize(prefix + cboItemsRes.getSelectedItem().toString().split(":")[0]);
        }
    }//GEN-LAST:event_btnDoVisActionPerformed

    private void rdOpt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdOpt1ActionPerformed
        prefix = rdOpt1.getText().split("- ")[1];
    }//GEN-LAST:event_rdOpt1ActionPerformed

    private void rdOpt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdOpt2ActionPerformed
        prefix = rdOpt2.getText().split("- ")[1];
    }//GEN-LAST:event_rdOpt2ActionPerformed

    private void rdOpt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdOpt3ActionPerformed
        prefix = "";
    }//GEN-LAST:event_rdOpt3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoVis;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup btngType;
    private javax.swing.JComboBox cboItemsRes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rdOpt1;
    private javax.swing.JRadioButton rdOpt2;
    private javax.swing.JRadioButton rdOpt3;
    // End of variables declaration//GEN-END:variables
}
