/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bdsiproject;

import javax.swing.UIManager;

/**
 *
 * @author usuario07
 */
public class Test extends javax.swing.JFrame {

    PythonConnector pc;

    /**
     * Creates new form Test
     */
    public Test() {
        try {
            pc = new PythonConnector();
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            initComponents();
            this.setLocationRelativeTo(null);
            loadData(0, "");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngVis = new javax.swing.ButtonGroup();
        btngComp = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboItemsVis = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        rdHsa = new javax.swing.JRadioButton();
        rdKo = new javax.swing.JRadioButton();
        rdEc = new javax.swing.JRadioButton();
        btnDoVis = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboItemsComp1 = new javax.swing.JComboBox();
        cboItemsComp2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        rdEc2 = new javax.swing.JRadioButton();
        rdKo2 = new javax.swing.JRadioButton();
        rdHsa2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btnDoComp = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setText("Tipo de PATHWAY:");

        jLabel4.setText("Por favor, seleccione el PATHWAY que desee visualizar:");

        btngVis.add(rdHsa);
        rdHsa.setSelected(true);
        rdHsa.setText("HSA");
        rdHsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdHsaActionPerformed(evt);
            }
        });

        btngVis.add(rdKo);
        rdKo.setText("KO");
        rdKo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdKoActionPerformed(evt);
            }
        });

        btngVis.add(rdEc);
        rdEc.setText("EC");
        rdEc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdEcActionPerformed(evt);
            }
        });

        btnDoVis.setText("Visualizar");
        btnDoVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoVisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboItemsVis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdHsa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdKo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdEc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDoVis, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboItemsVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rdHsa)
                    .addComponent(rdKo)
                    .addComponent(rdEc)
                    .addComponent(btnDoVis))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Visualizar", jPanel1);

        jLabel2.setText("Por favor, seleccione el primer PATHWAY a comparar:");

        jLabel3.setText("Por favor, seleccione el segundo PATHWAY a comparar:");

        btngComp.add(rdEc2);
        rdEc2.setText("EC");
        rdEc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdEc2ActionPerformed(evt);
            }
        });

        btngComp.add(rdKo2);
        rdKo2.setText("KO");
        rdKo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdKo2ActionPerformed(evt);
            }
        });

        btngComp.add(rdHsa2);
        rdHsa2.setSelected(true);
        rdHsa2.setText("HSA");
        rdHsa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdHsa2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo de PATHWAY:");

        btnDoComp.setText("Comparar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboItemsComp1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboItemsComp2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdHsa2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdKo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdEc2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDoComp, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboItemsComp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboItemsComp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdHsa2)
                    .addComponent(rdKo2)
                    .addComponent(rdEc2)
                    .addComponent(btnDoComp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Comparar", jPanel2);

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDoVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoVisActionPerformed
        pc.visualize(cboItemsVis.getSelectedItem().toString().split(":")[0]);
    }//GEN-LAST:event_btnDoVisActionPerformed

    private void rdHsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdHsaActionPerformed
        loadData(1, "hsa");
    }//GEN-LAST:event_rdHsaActionPerformed

    private void rdKoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdKoActionPerformed
        loadData(1, "ko");
    }//GEN-LAST:event_rdKoActionPerformed

    private void rdEcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdEcActionPerformed
        loadData(1, "ec");
    }//GEN-LAST:event_rdEcActionPerformed

    private void rdHsa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdHsa2ActionPerformed
        loadData(2, "hsa");
    }//GEN-LAST:event_rdHsa2ActionPerformed

    private void rdKo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdKo2ActionPerformed
        loadData(2, "ko");
    }//GEN-LAST:event_rdKo2ActionPerformed

    private void rdEc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdEc2ActionPerformed
        loadData(2, "ec");
    }//GEN-LAST:event_rdEc2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoComp;
    private javax.swing.JButton btnDoVis;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup btngComp;
    private javax.swing.ButtonGroup btngVis;
    private javax.swing.JComboBox cboItemsComp1;
    private javax.swing.JComboBox cboItemsComp2;
    private javax.swing.JComboBox cboItemsVis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rdEc;
    private javax.swing.JRadioButton rdEc2;
    private javax.swing.JRadioButton rdHsa;
    private javax.swing.JRadioButton rdHsa2;
    private javax.swing.JRadioButton rdKo;
    private javax.swing.JRadioButton rdKo2;
    // End of variables declaration//GEN-END:variables

    private void loadData(int type, String item) {
        switch (type) {
            case 0:
                for (Object object : pc.getItems("hsa")) {
                    cboItemsVis.addItem((String) object);
                    cboItemsComp1.addItem((String) object);
                    cboItemsComp2.addItem((String) object);
                }
                break;
            case 1:
                cboItemsVis.removeAllItems();
                for (Object object : pc.getItems(item)) {
                    cboItemsVis.addItem((String) object);
                }
                break;
            case 2:
                cboItemsComp1.removeAllItems();
                cboItemsComp2.removeAllItems();
                for (Object object : pc.getItems(item)) {
                    cboItemsComp1.addItem((String) object);
                    cboItemsComp2.addItem((String) object);
                }
                break;
        }
    }
}
